name: TheCore
version: 1.0
description: HCF
authors: [subbotted]
main: me.esshd.hcf.HCF
softdepend: [ProtocolLib, Essentials]

permissions:
    Core.staff:
      description: Main staff permission.
    Core.staff.advanced:
      description: Advanced staff permission.
    
commands:
  #focus:
  #cobble:
  help:
    aliases: [help, teamspeak, website]
  endportal:
  angle:
    description: Check your yaw and pitch position.
  loot:
    description: Base loot command.
  conquest:
    description: Command used to handle Conquest events.
  economy:
    aliases: [$, bal, money, eco, econ]
    description: Command used to modify the economy.
  end:
    description: Command used to close or open the end.
  eotw:
    aliases: [endoftheworld]
    description: Sets if the server is in End of the World mode.
  event:
    description: Command used to manage minigame events.
  faction:
    aliases: [f, fac]
    description: Faction related commands.
  gopple:
    description: Command to check remaining OP apple cooldown time.
    aliases: [opple, goppletimer, goppletime, oppletimer, oppletime]
  hcf:
    aliases: [thecore, core, hardcorefactions, hcfactions]
  koth:
    description: Make or delete KotH arenas.
  location:
    aliases: [loc]
    description: Check the faction location of a player.
  logout:
    aliases: [disconnect]
    description: Command to safely logout without an NPC spawning.
  mapkit:
    aliases: [viewkit]
    description: Used to check the current map restrictions.
  pay:
    aliases: [p2p]
    description: Allow players to pay money.
  pvptimer:
    aliases: [pvp]
    description: Command to enable or disable pvp timer protection.
  regen:
    description: Check ETA until a faction is able to regenerate DTR.
  servertime:
    description: Checks the date and time of server.
  sotw:
    aliases: [startoftheworld]
    description: Command used to manage start of the world.
  spawncannon:
    aliases: [cannon, playercannon]
    description: Shoots you into the warzone.
  timer:
    description: Command to manage timers.
  togglefd:
    aliases: [tfd]
    description: Toggle found diamond ore notifications.
  togglecapzoneentry:
    aliases: [togglecapentry]
    description: Command used to hide or show capture zone entry messages.
  togglelightning:
    aliases: [lightningtoggle, togglestrikes]
    description: Toggles the lightning strikes for when a player dies.
  togglesidebar:
    aliases: [sidebartoggle, sidebar, hud, togglehud]
    description: Toggles the scoreboard timers displayed on sidebar.
  give:
  toggledonoronly:
    description: Turns the server to Donor only mode.
    aliases: [donoronly, donormode]
  history:
  request:
  staffmode:
  announcement:
    aliases: ["announce", "ann"]
  list:
    aliases: [who]
  note:
  copyinv:
  amivis:
    aliases: ["amivanish", "amivanished", "?invis", "?v", "?vis", "invis?", "vis?", "v?"]
    description: Command used to check if visible.
  back:
    description: Teleport to last known location.
  broadcast:
    aliases: [bc]
    description: Broadcast a server message.
  clearchat:
    aliases: [cc]
    description: Clear the chat history.
  clearinv:
    aliases: [ci, clear, cpinv]
    description: Clears a player inventory.
  enchant:
    description: Enchant an item.
  entities:
    description: Check the entities in a world.
  fly:
    description: Toggle flight for a player.
  feed:
    aliases: [feed]
    description: Feed a player.
  freeze:
    description: Command used to freeze players.
    aliases: [ss]
  gamemode:
    aliases: [gm]
    description: Update a players gamemode.
  hat:
    description: Wear something as a hat.
  heal:
    description: Heal a player.
  id:
    description: Check the id of an item.
  ignore:
    description: Ignore a player from messaging you
  invsee:
    aliases: [inventory, inventorysee, inv]
    description: View a players inventory.
  iphistory:
    description: Check the history an IP address or player.
  kill:
    aliases: [suicide, slay]
    description: Kill a player.
  kit:
    description: Command to apply or use kits.
  lag:
    description: Check the server lag.
  message:
    aliases: [m, msg, tell, whisper, w]
    description: Messsage an online player.
  socialspy:
    aliases: [ms, msgspy, pmspy, whisperspy, privatemessagespy, tellspy]
    description: Command used to spy on pm's of players.
  more:
    description: Give yourself more of an item.
  mutechat:
    aliases: [mc, rc, restrictchat, disablechat]
    description: Restricts the use of global chat.
  near:
    description: Check nearby entities to a player.
  ping:
    aliases: [p]
    description: Checks the ping of a player.
  playtime:
    aliases: [pt]
    description: Track a players total playtime of the map.
  playertime:
    aliases: [ptime]
    description: Shows your player time.
  position:
    description: Checks the position of a player.
  removeentity:
    aliases: [reme, rem]
    description: Remove entities from the server.
  rename:
    description: Command used to rename items.
  repair:
    aliases: [fix]
    description: Allows the repairing of tools.
  report:
    description: Report
  reply:
    aliases: [r]
    description: Reply to a player message.
  rules:
    description: Shows the server rules.
  seen:
    description: Checks when a player was last seen.
  setmaxplayers:
    description: Set the maximum player count.
  skull:
    description: Spawn the skull of a player.
  slowchat:
    aliases: [slow]
    description: Sets a delay between chat messages.
  sounds:
    aliases: [pmsounds, togglepmsounds, messagingsounds]
    description: Toggles messaging sounds
  speed:
    description: Set your walk or fly speed.
  staffchat:
    aliases: [sc, ac]
    description: Speak in staff chat mode only.
  stoplag:
  createworld:
  sudo:
    description: Force another player to run a command.
  teleport:
    aliases: [tp]
    description: Teleport to a player or location.
  teleportall:
    aliases: [tpall]
    description: Teleport all online players somewhere.
  teleporthere:
    aliases: [tphere]
    description: Teleport a player to self.
  togglechat:
    aliases: [tgc, toggleglobalchat]
    description: Toggles global chat visibility on or off.
  togglemessages:
    aliases: [togglepm, toggleprivatemessages]
    description: Disable private messages.
  top:
    description: Teleport to highest spot of world
  unfreeze:
    description: Un-freezes' a player.
  uptime:
    description: Check how long a server has been up for.
  vanish:
    aliases: [v, vis, vanish, invis]
    description: Hide yourself from other players.
  whois:
    description: Check information about a player.
  world:
    description: Change your current world.